const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='cclExamLabV2';
const RAW_MAIN='https://raw.githubusercontent.com/SzeChunYiu/CCL-exam/main/';
const localHost=()=>['localhost','127.0.0.1'].includes(location.hostname);
const asset=(path)=>localHost()?`/${path}`:`${RAW_MAIN}${path}`;
const getJSON=(path)=>fetch(asset(path),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${path} failed (${r.status})`);return r.json()});
const state={dialogues:[],byId:{},glossary:[],studyIndex:[],summary:null,audioManifest:null,config:null,user:null,view:'dashboard',session:null,timer:null,voices:[],media:null,recorder:null,chunks:[],recordings:{},audioEngine:null,speechDelay:null};
const ERROR_TAGS=['Omission','Addition','Distortion','Number/date','Name/detail','Terminology','English delivery','Cantonese delivery','Register'];

function loadUser(){
 const defaults={favorites:[],weak:[],history:[],completed:[],prefs:{practiceRate:1}};
 try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}');const u=Object.assign({},defaults,raw);u.prefs=Object.assign({},defaults.prefs,raw.prefs||{});return u}catch{return defaults}
}
function saveUser(){localStorage.setItem(STORE,JSON.stringify(state.user))}
function uid(){return`${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function fmtTime(s){s=Math.max(0,Math.floor(s||0));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function labelMode(m){return({mock:'Mock exam',practice:'Topic practice',drill:'Quick drill'}[m]||m)}
function topics(){return [...new Set(state.dialogues.map(d=>d.topic))].sort()}
function testPairs(){const p=state.config?.mockPairs;if(Array.isArray(p)&&p.length)return p.map(x=>x.map(id=>state.byId[id])).filter(x=>x.length===2&&x.every(Boolean));let a=[];for(let i=0;i<state.dialogues.length;i+=2)a.push([state.dialogues[i],state.dialogues[i+1]]);return a}
function completedSet(){return new Set(state.user.completed)}
function isFav(id){return state.user.favorites.includes(id)}
function isWeak(id,n){return state.user.weak.includes(`${id}-${n}`)}
function toggleFav(id){state.user.favorites=isFav(id)?state.user.favorites.filter(x=>x!==id):[...state.user.favorites,id];saveUser();renderLibrary()}
function markCompleted(id){if(!state.user.completed.includes(id)){state.user.completed.push(id);saveUser()}}
function toggleWeak(id,n,on){const k=`${id}-${n}`,has=state.user.weak.includes(k);if(on&&!has)state.user.weak.push(k);if(!on&&has)state.user.weak=state.user.weak.filter(x=>x!==k);saveUser()}

function nav(active='dashboard'){
 const items=[['dashboard','Dashboard'],['library','Library'],['vocabulary','Vocabulary'],['study','Study'],['history','Results']];
 return `<header class="topbar"><div class="brand" onclick="go('dashboard')" style="cursor:pointer"><div class="mark">CCL</div><div>CCL Exam Lab<div class="kicker">English ⇄ Cantonese</div></div></div><nav class="nav">${items.map(([v,l])=>`<button class="${active===v?'active':''}" onclick="go('${v}')">${l}</button>`).join('')}</nav><span class="pill ${state.audioManifest?'ok':'warn'}">${state.audioManifest?'Calibrated MP3 ready':'Speech fallback'}</span></header>`
}
function page(inner,active='dashboard'){return `<main class="shell">${nav(active)}${inner}<div class="footer">Original English–Cantonese CCL-style training material. Practice scores are study feedback, not official NAATI results.</div></main>`}
function go(v){stopAll();state.view=v;state.session=null;window.scrollTo(0,0);({dashboard:renderDashboard,library:renderLibrary,vocabulary:renderVocabulary,study:renderStudy,history:renderHistory}[v]||renderDashboard)()}

async function boot(){
 state.user=loadUser();
 if('speechSynthesis'in window){const load=()=>{state.voices=speechSynthesis.getVoices()||[];if(state.view==='dashboard'&&state.summary)renderDashboard()};load();speechSynthesis.onvoiceschanged=load}
 try{
  const [d,g,si,sm,cfg]=await Promise.all([
   getJSON('data/dialogues.json'),getJSON('data/glossary.json'),getJSON('data/study_index.json'),getJSON('data/site_summary.json'),getJSON('data/config.json')
  ]);
  let am=null;
  if(cfg.audioManifestUrl){am=await fetch(cfg.audioManifestUrl,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)}
  if(!am){am=await getJSON('data/audio_manifest.json').catch(()=>null)}
  state.dialogues=d;state.byId=Object.fromEntries(d.map(x=>[x.id,x]));state.glossary=g;state.studyIndex=si;state.summary=sm;state.config=cfg;state.audioManifest=am;state.audioEngine=new AudioEngine();renderDashboard();
 }catch(e){$('#app').innerHTML=page(`<div class="card"><h2>Could not load the practice bank</h2><p class="muted">${esc(e.message)}</p></div>`)}
}

function audioSettingsHTML(){
 const ref=state.config?.audioCalibration||{},gen=state.audioManifest?.calibration||{};
 return `<section class="section card"><div class="section-head"><div><div class="eyebrow">Audio realism</div><h2>Sample-calibrated MP3 baseline</h2><p class="muted">Mock mode always uses the bundled 1.0× MP3 source audio when available. The full generated bank measures about <strong>${gen.generatedEnglishWpm||'160'} English wpm</strong> and <strong>${gen.generatedCantoneseEquivalentWpm||'180'} Cantonese English-equivalent wpm</strong>, calibrated against reference averages of roughly ${ref.englishTargetWpm||160} / ${ref.cantoneseEnglishEquivalentTargetWpm||179}.</p></div></div><div class="notice">Training mode can use 0.9×, 1.0× or 1.08×. Browser speech is an emergency fallback only; its exact rate depends on the device and is not treated as exam-calibrated audio.</div></section>`
}

function renderDashboard(){
 const h=state.user.history, scored=h.filter(x=>Number.isFinite(x.score));const avg=scored.length?Math.round(scored.reduce((a,x)=>a+x.score,0)/scored.length):'—';
 const inner=`<section class="hero"><div class="card"><div class="eyebrow">Full exam workspace</div><h1>Practise like<br>it matters.</h1><p>Train English ⇄ Cantonese interpreting with strict two-dialogue mocks, topic practice, quick drills, calibrated MP3 source audio, Australian terminology, study materials and persistent performance history.</p><div class="actions"><button class="btn primary" onclick="startMock(0)">Start Mock Test 01</button><button class="btn secondary" onclick="randomMock()">Random mock</button></div></div><div class="card"><div class="eyebrow">Your dashboard</div><h2>Progress</h2><div class="stats"><div class="stat"><strong>${state.summary.dialogues}</strong><span class="muted">dialogues</span></div><div class="stat"><strong>${state.summary.mock_tests}</strong><span class="muted">mock exams</span></div><div class="stat"><strong>${state.user.completed.length}</strong><span class="muted">dialogues completed</span></div><div class="stat"><strong>${avg}${avg==='—'?'':'%'}</strong><span class="muted">avg practice rating</span></div></div><div class="notice" style="margin-top:12px">Bundled MP3 is the default and the 1.0× mock pace is calibrated against the measured NAATI Cantonese practice-sample averages. Browser speech is used only if MP3 delivery fails.</div></div></section>
 <section class="section"><div class="section-head"><div><div class="eyebrow">Six-part training system</div><h2>Choose your mode</h2></div></div><div class="mode-grid">
 ${modeCard('01','Mock Exam','Two dialogues, 20-minute practice clock, hidden scripts, one free repeat per dialogue, optional recording, answers only after finishing.',"renderMockPicker()")}
 ${modeCard('02','Topic Practice','Choose a topic and dialogue. Interpret one segment at a time, reveal the source/model, tag errors and repeat freely.',"renderPracticeSetup()")}
 ${modeCard('03','Quick Drill','Ten random segments focused on fast retrieval, numbers, terminology and direction switching.',"renderDrillSetup()")}
 ${modeCard('04','Performance','Review stored attempts, weak topics, repeat use and your most common self-tagged error patterns.',"go('history')")}
 ${modeCard('05','100-dialogue Library','Search and filter all scenarios by topic, difficulty, completion and favourites.',"go('library')")}
 ${modeCard('06','Study & Vocabulary','198 Australian bilingual terms plus the study guide, note-taking drills, self-review material and reference notes.',"go('study')")}
 </div></section>${audioSettingsHTML()}`;
 $('#app').innerHTML=page(inner,'dashboard')
}
function modeCard(n,t,p,act){return `<article class="card mode-card"><div><div class="eyebrow">${n}</div><h3>${t}</h3><p>${p}</p></div><div class="actions"><button class="btn" onclick="${act}">Open →</button></div></article>`}

function renderMockPicker(){
 const pairs=testPairs();
 $('#app').innerHTML=page(`<section class="section"><div class="section-head"><div><div class="eyebrow">Strict mode</div><h2>Choose a mock exam</h2><p class="muted">Each mock pairs two dialogues. Scripts and model interpretations stay hidden until you finish.</p></div><button class="btn secondary" onclick="randomMock()">Random mock</button></div><div class="grid">${pairs.map((p,i)=>`<article class="card library-card"><span class="pill accent">Mock ${String(i+1).padStart(2,'0')}</span><h3>${esc(p[0].title)}</h3><div class="muted">${esc(p[0].topic)} · ${p[0].difficulty}</div><p class="muted">+</p><h3>${esc(p[1].title)}</h3><div class="muted">${esc(p[1].topic)} · ${p[1].difficulty}</div><div class="actions"><button class="btn primary" onclick="startMock(${i})">Start exam</button></div></article>`).join('')}</div></section>`,'dashboard')
}
function randomMock(){startMock(Math.floor(Math.random()*testPairs().length))}
function startMock(i){
 stopAll();const pair=testPairs()[i];state.recordings={};state.session={id:uid(),mode:'mock',testIndex:i,dialogueIds:pair.map(d=>d.id),di:0,si:0,repeats:{[pair[0].id]:0,[pair[1].id]:0},played:{},notes:{},marks:{},startedAt:Date.now(),endedAt:null,timeLeft:1200,interpretTimer:null,audioMode:null};state.view='mock';startClock();renderMock();
}
function startClock(){clearInterval(state.timer);state.timer=setInterval(()=>{if(!state.session||state.session.mode!=='mock')return;state.session.timeLeft=Math.max(0,1200-Math.floor((Date.now()-state.session.startedAt)/1000));const t=$('#timer');if(t){t.textContent=fmtTime(state.session.timeLeft);t.classList.toggle('warn',state.session.timeLeft<180);t.classList.toggle('danger',state.session.timeLeft<60)}if(state.session.timeLeft<=0)finishSession()},1000)}
function currentMock(){const s=state.session,d=state.byId[s.dialogueIds[s.di]];return {d,seg:d.segments[s.si]}}
function sessionKey(did,n){return`${did}-${n}`}
function renderMock(){
 const s=state.session,{d,seg}=currentMock(),total=s.dialogueIds.reduce((a,id)=>a+state.byId[id].segments.length,0),done=s.dialogueIds.slice(0,s.di).reduce((a,id)=>a+state.byId[id].segments.length,0)+s.si;
 $('#app').innerHTML=`<div class="exam-head"><div class="exam-head-inner"><div><strong>Mock ${String(s.testIndex+1).padStart(2,'0')}</strong><div class="kicker">Dialogue ${s.di+1} of 2</div></div><div id="timer" class="timer">${fmtTime(s.timeLeft)}</div><button class="btn danger" onclick="finishSession()">Finish exam</button></div><div class="progress"><span style="width:${done/total*100}%"></span></div></div><main class="exam-shell"><div class="dialogue-banner"><div><span class="pill">${esc(d.topic)}</span> <span class="pill">${d.difficulty}</span><h2>${esc(d.title)}</h2><div class="muted">Segment ${seg.n} of ${d.segments.length}</div></div><div class="repeat-box">Repeats this dialogue<br><strong>${s.repeats[d.id]||0}</strong><div>${(s.repeats[d.id]||0)<=1?'First repeat is allowance':'Extra repeats used'}</div></div></div><section class="card segment-card"><div class="segment-num">SOURCE SEGMENT ${seg.n}</div><div class="direction">${seg.source_lang==='en'?'ENGLISH → CANTONESE':'CANTONESE → ENGLISH'}</div><div class="listen-icon">◖))</div><div id="audioStatus" class="prompt-hidden">Source text is hidden. Play the segment, wait for the chime, then interpret in first person.</div><div id="interpretCount" class="interpret-count"></div><div class="actions" style="justify-content:center"><button id="playBtn" class="btn primary" onclick="playSessionSegment(false)">▶ Play segment</button><button class="btn" onclick="playSessionSegment(true)">↻ Repeat</button></div><div class="recorder"><div id="recStatus" class="muted">Optional: record your interpretation for the review screen.</div><div class="actions" style="justify-content:center"><button id="recordBtn" class="btn" onclick="toggleRecord()">● Start recording</button><button class="btn" onclick="playMyRecording('${d.id}',${seg.n})" ${state.recordings[sessionKey(d.id,seg.n)]?'':'disabled'}>Listen to mine</button></div></div><textarea id="note" class="notes" placeholder="Optional shorthand / notes…" oninput="state.session.notes['${sessionKey(d.id,seg.n)}']=this.value">${esc(s.notes[sessionKey(d.id,seg.n)]||'')}</textarea><div class="actions" style="justify-content:center"><button class="btn primary" onclick="nextMock()">${s.di===1&&s.si===d.segments.length-1?'Finish exam':'Submit & next →'}</button></div><p class="kicker">Practice rule: start interpreting promptly after the chime. The five-second cue is shown only as a training aid.</p></section></main>`
}
async function playSessionSegment(repeat){const {d,seg}=currentMock();if(repeat)state.session.repeats[d.id]=(state.session.repeats[d.id]||0)+1;state.session.played[sessionKey(d.id,seg.n)]=(state.session.played[sessionKey(d.id,seg.n)]||0)+1;renderRepeatOnly();await playSource(d,seg,1,()=>startInterpretCountdown())}
function renderRepeatOnly(){const box=$('.repeat-box');if(!box)return;const {d}=currentMock(),n=state.session.repeats[d.id]||0;box.innerHTML=`Repeats this dialogue<br><strong>${n}</strong><div>${n<=1?'First repeat is allowance':'Extra repeats used'}</div>`}
function startInterpretCountdown(){clearInterval(state.session?.interpretTimer);let n=5;const el=$('#interpretCount');if(!el)return;el.textContent=`Interpret now · ${n}`;state.session.interpretTimer=setInterval(()=>{n--;if(!$('#interpretCount')){clearInterval(state.session.interpretTimer);return}$('#interpretCount').textContent=n>0?`Interpret now · ${n}`:'Interpret now';if(n<=0)clearInterval(state.session.interpretTimer)},1000)}
function nextMock(){stopPlayback();if(state.recorder?.state==='recording')state.recorder.stop();const s=state.session,d=state.byId[s.dialogueIds[s.di]];if(s.si<d.segments.length-1){s.si++;renderMock();return}markCompleted(d.id);if(s.di===0){s.di=1;s.si=0;renderMock();return}markCompleted(state.byId[s.dialogueIds[1]].id);finishSession()}

function renderPracticeSetup(){
 const t=topics();$('#app').innerHTML=page(`<section class="hero"><div class="card"><div class="eyebrow">Training mode</div><h1 style="font-size:52px">Topic practice</h1><p>Choose a topic and difficulty. Source text stays hidden until you attempt the interpretation, then you can reveal the model, tag errors and repeat freely.</p></div><div class="card"><h2>Set up practice</h2><div class="setup"><label><div class="kicker">Topic</div><select id="pTopic" class="select"><option value="All">All topics</option>${t.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label><div class="kicker">Difficulty</div><select id="pDiff" class="select"><option value="All">All levels</option><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><div class="actions"><button class="btn primary" onclick="randomPracticeFromSetup()">Start random dialogue</button><button class="btn" onclick="go('library')">Browse library</button></div></div></section>`,'dashboard')
}
function randomPracticeFromSetup(){const t=$('#pTopic').value,diff=$('#pDiff').value;const pool=state.dialogues.filter(d=>(t==='All'||d.topic===t)&&(diff==='All'||d.difficulty===diff));startPractice(pool[Math.floor(Math.random()*pool.length)].id)}
function startPractice(id,si=0){stopAll();state.recordings={};state.session={id:uid(),mode:'practice',dialogueIds:[id],di:0,si,notes:{},marks:{},revealed:{},startedAt:Date.now(),endedAt:null};state.view='practice';renderPractice()}
function currentPractice(){const d=state.byId[state.session.dialogueIds[0]],seg=d.segments[state.session.si];return {d,seg}}
function renderPractice(){
 const s=state.session,{d,seg}=currentPractice(),k=sessionKey(d.id,seg.n),revealed=!!s.revealed[k],m=s.marks[k]||{rating:null,tags:[]};
 $('#app').innerHTML=page(`<div class="dialogue-banner"><div><span class="pill">${esc(d.topic)}</span> <span class="pill">${d.difficulty}</span><h2>${esc(d.title)}</h2><div class="muted">Segment ${seg.n} of ${d.segments.length} · ${seg.source_lang==='en'?'English → Cantonese':'Cantonese → English'}</div></div><button class="btn" onclick="go('library')">Exit practice</button></div><section class="card segment-card"><div class="listen-icon">◖))</div><div id="audioStatus" class="prompt-hidden">Listen first. Keep the script hidden until you have interpreted the segment.</div><div class="toolbar" style="justify-content:center"><label class="pill">Speed <select class="select" id="practiceRate" onchange="setRate(this.value)" style="padding:4px;border:0"><option value="0.9" ${state.user.prefs.practiceRate==.9?'selected':''}>0.9×</option><option value="1" ${state.user.prefs.practiceRate==1?'selected':''}>1.0× sample pace</option><option value="1.08" ${state.user.prefs.practiceRate==1.08?'selected':''}>1.08×</option></select></label></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="playPracticeSource()">▶ Play source</button><button class="btn" onclick="playPracticeSource()">↻ Replay freely</button></div><div class="recorder"><div id="recStatus" class="muted">Optional: record your interpretation.</div><div class="actions" style="justify-content:center"><button id="recordBtn" class="btn" onclick="toggleRecord()">● Start recording</button><button class="btn" onclick="playMyRecording('${d.id}',${seg.n})" ${state.recordings[k]?'':'disabled'}>Listen to mine</button></div></div><textarea class="notes" placeholder="Notes / shorthand…" oninput="state.session.notes['${k}']=this.value">${esc(s.notes[k]||'')}</textarea><div class="actions" style="justify-content:center">${revealed?'':'<button class="btn secondary" onclick="revealPractice()">Reveal & compare</button>'}</div>${revealed?compareBlock(d,seg,m,'practice'):''}</section></main>`,'library')
}
function setRate(v){state.user.prefs.practiceRate=Number(v);saveUser()}
async function playPracticeSource(){const {d,seg}=currentPractice();await playSource(d,seg,state.user.prefs.practiceRate||1,()=>{const el=$('#audioStatus');if(el)el.textContent='Interpret now. When finished, reveal and compare.'})}
function revealPractice(){const {d,seg}=currentPractice();state.session.revealed[sessionKey(d.id,seg.n)]=true;renderPractice()}
function compareBlock(d,seg,m,ctx){const k=sessionKey(d.id,seg.n);return `<div class="compare-grid"><div><div class="kicker">Source</div><div class="source-box">${esc(seg.source)}</div></div><div><div class="kicker">Model interpretation</div><div class="model-box">${esc(seg.model)}</div></div></div><div style="text-align:left;margin-top:15px"><div class="kicker">How did your meaning transfer go?</div><div class="rating-row">${[['strong','Strong'],['minor','Minor issue'],['needs','Needs work']].map(([v,l])=>`<button class="rating ${m.rating===v?'on':''}" onclick="setMark('${k}','rating','${v}','${ctx}')">${l}</button>`).join('')}</div><div class="kicker" style="margin-top:13px">Error tags</div><div class="rating-row">${ERROR_TAGS.map(t=>`<button class="tag ${(m.tags||[]).includes(t)?'on':''}" onclick="setMark('${k}','tag','${esc(t)}','${ctx}')">${esc(t)}</button>`).join('')}</div><div class="actions"><button class="btn" onclick="${ctx==='drill'?'playDrillSource()':'playPracticeSource()'}">Replay source</button>${ctx==='practice'?`<button class="btn primary" onclick="nextPractice()">${state.session.si===d.segments.length-1?'Finish dialogue':'Next segment →'}</button>`:''}</div></div>`}
function setMark(k,type,val,ctx){const s=state.session;s.marks[k]=s.marks[k]||{rating:null,tags:[]};if(type==='rating'){s.marks[k].rating=val;const [id,n]=splitKey(k);toggleWeak(id,n,val==='needs')}else{s.marks[k].tags=s.marks[k].tags||[];s.marks[k].tags=s.marks[k].tags.includes(val)?s.marks[k].tags.filter(x=>x!==val):[...s.marks[k].tags,val]}if(ctx==='practice')renderPractice();else if(ctx==='drill')renderDrill();else renderPerformance()}
function splitKey(k){const m=k.match(/^(D\d+)-(\d+)$/);return[m?.[1],Number(m?.[2])||0]}
function nextPractice(){const s=state.session,{d}=currentPractice();if(s.si<d.segments.length-1){s.si++;renderPractice();return}markCompleted(d.id);s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}

function renderDrillSetup(){
 $('#app').innerHTML=page(`<section class="hero"><div class="card"><div class="eyebrow">Retrieval training</div><h1 style="font-size:52px">Quick drill</h1><p>Ten unseen segments. Filter by topic and direction, switch quickly between English and Cantonese, reveal only after you interpret.</p></div><div class="card"><h2>Set up drill</h2><label><div class="kicker">Topic</div><select id="dTopic" class="select"><option value="All">All topics</option>${topics().map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label style="display:block;margin-top:10px"><div class="kicker">Direction</div><select id="dDir" class="select"><option value="All">Both directions</option><option value="en">English → Cantonese</option><option value="yue">Cantonese → English</option></select></label><div class="actions"><button class="btn primary" onclick="startDrill()">Start 10-segment drill</button></div></div></section>`,'dashboard')
}
function startDrill(){const t=$('#dTopic').value,dir=$('#dDir').value;let pool=[];state.dialogues.filter(d=>t==='All'||d.topic===t).forEach(d=>d.segments.filter(s=>dir==='All'||s.source_lang===dir).forEach(seg=>pool.push({did:d.id,n:seg.n})));pool=shuffle(pool).slice(0,10);state.session={id:uid(),mode:'drill',queue:pool,qi:0,marks:{},notes:{},revealed:{},startedAt:Date.now(),endedAt:null};state.recordings={};renderDrill()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function currentDrill(){const q=state.session.queue[state.session.qi],d=state.byId[q.did],seg=d.segments[q.n-1];return{d,seg}}
function renderDrill(){const s=state.session,{d,seg}=currentDrill(),k=sessionKey(d.id,seg.n),m=s.marks[k]||{rating:null,tags:[]},rev=s.revealed[k];$('#app').innerHTML=page(`<div class="dialogue-banner"><div><span class="pill">Quick drill ${s.qi+1}/10</span> <span class="pill">${esc(d.topic)}</span><h2>${seg.source_lang==='en'?'English → Cantonese':'Cantonese → English'}</h2></div><button class="btn" onclick="go('dashboard')">Exit drill</button></div><section class="card segment-card"><div class="listen-icon">◖))</div><div id="audioStatus" class="prompt-hidden">Listen, interpret, then reveal.</div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="playDrillSource()">▶ Play source</button><button class="btn" onclick="playDrillSource()">↻ Replay</button></div>${rev?compareBlock(d,seg,m,'drill'):`<div class="actions" style="justify-content:center"><button class="btn secondary" onclick="state.session.revealed['${k}']=true;renderDrill()">Reveal & compare</button></div>`}${rev?`<div class="actions" style="justify-content:center"><button class="btn primary" onclick="nextDrill()">${s.qi===9?'Finish drill':'Next drill →'}</button></div>`:''}</section>`,'dashboard')}
async function playDrillSource(){const {d,seg}=currentDrill();await playSource(d,seg,state.user.prefs.practiceRate||1,()=>{const e=$('#audioStatus');if(e)e.textContent='Interpret now, then reveal.'})}
function nextDrill(){const s=state.session;if(s.qi<s.queue.length-1){s.qi++;renderDrill();return}s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}

function renderLibrary(){
 const favs=state.user.favorites,done=completedSet();
 $('#app').innerHTML=page(`<section class="section"><div class="section-head"><div><div class="eyebrow">100-dialogue bank</div><h2>Practice library</h2><p class="muted">Search Australian scenarios, filter by topic/difficulty, favourite difficult dialogues and reopen completed material.</p></div><button class="btn primary" onclick="renderPracticeSetup()">Random topic practice</button></div><div class="toolbar"><input id="libSearch" class="input" placeholder="Search title, term, ABN, Medicare, tenancy…" oninput="filterLibrary()"><select id="libTopic" class="select" onchange="filterLibrary()"><option value="All">All topics</option>${topics().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="libDiff" class="select" onchange="filterLibrary()"><option value="All">All levels</option><option>Easy</option><option>Medium</option><option>Hard</option></select><select id="libStatus" class="select" onchange="filterLibrary()"><option value="All">All status</option><option value="New">Not completed</option><option value="Done">Completed</option><option value="Fav">Favourites</option></select></div><div id="libraryGrid" class="grid"></div></section>`,'library');filterLibrary()
}
function filterLibrary(){const q=($('#libSearch')?.value||'').toLowerCase(),t=$('#libTopic')?.value||'All',df=$('#libDiff')?.value||'All',st=$('#libStatus')?.value||'All',done=completedSet();let ds=state.dialogues.filter(d=>(!q||`${d.id} ${d.title} ${d.term} ${d.term_yue} ${d.topic}`.toLowerCase().includes(q))&&(t==='All'||d.topic===t)&&(df==='All'||d.difficulty===df)&&(st==='All'||(st==='New'&&!done.has(d.id))||(st==='Done'&&done.has(d.id))||(st==='Fav'&&isFav(d.id))));const el=$('#libraryGrid');if(!el)return;el.innerHTML=ds.length?ds.map(d=>`<article class="card library-card"><button class="star ${isFav(d.id)?'on':''}" onclick="toggleFav('${d.id}')">★</button><span class="pill accent">${d.id}</span> <span class="pill">${d.difficulty}</span> ${done.has(d.id)?'<span class="pill ok">Completed</span>':''}<h3>${esc(d.title)}</h3><div class="muted">${esc(d.topic)}</div><p><strong>${esc(d.term)}</strong><br><span class="muted">${esc(d.term_yue)}</span></p><div class="actions"><button class="btn primary" onclick="startPractice('${d.id}')">Practice</button><button class="btn" onclick="startMock(${d.mock-1})">Paired mock ${String(d.mock).padStart(2,'0')}</button></div></article>`).join(''):`<div class="card empty">No dialogues match these filters.</div>`}

function renderVocabulary(){
 $('#app').innerHTML=page(`<section class="section"><div class="section-head"><div><div class="eyebrow">Australian terminology</div><h2>Vocabulary trainer</h2><p class="muted">${state.glossary.length} study equivalents. Keep Australian acronyms and branded terms where natural; focus on meaning transfer rather than rigid word-for-word substitution.</p></div></div><div class="toolbar"><input id="vSearch" class="input" placeholder="Search English or Cantonese…" oninput="filterVocab()"><select id="vTopic" class="select" onchange="filterVocab()"><option value="All">All topics</option>${[...new Set(state.glossary.map(x=>x.topic))].map(x=>`<option>${esc(x)}</option>`).join('')}</select><button class="btn" onclick="$$('.vocab-answer').forEach(x=>x.hidden=false)">Reveal all</button></div><div id="vocabGrid" class="vocab-grid"></div></section>`,'vocabulary');filterVocab()
}
function filterVocab(){const q=($('#vSearch')?.value||'').toLowerCase(),t=$('#vTopic')?.value||'All';const a=state.glossary.filter(x=>(t==='All'||x.topic===t)&&(!q||`${x.en} ${x.yue}`.toLowerCase().includes(q)));$('#vocabGrid').innerHTML=a.map((x,i)=>`<article class="vocab-card"><span class="pill">${esc(x.topic)}</span><strong style="margin-top:9px">${esc(x.en)}</strong><button class="btn ghost" style="padding-left:0" onclick="this.nextElementSibling.hidden=false;this.hidden=true">Reveal Cantonese</button><div class="vocab-answer" hidden>${esc(x.yue)}</div></article>`).join('')}

async function renderStudy(slug){
 slug=slug||state.studyIndex[0]?.slug;const tabs=state.studyIndex.map(x=>`<button class="btn ${x.slug===slug?'primary':''}" onclick="renderStudy('${x.slug}')">${esc(x.title)}</button>`).join('');$('#app').innerHTML=page(`<section class="section"><div class="section-head"><div><div class="eyebrow">Preparation material</div><h2>Study hub</h2></div><button class="btn" onclick="go('vocabulary')">Open vocabulary</button></div><div class="study-nav">${tabs}</div><article id="studyContent" class="card study-content"><p class="muted">Loading…</p></article></section>`,'study');try{$('#studyContent').innerHTML=await fetch(asset(`study/${slug}.html`),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Study file failed (${r.status})`);return r.text()})}catch(e){$('#studyContent').innerHTML=`<p>Could not load: ${esc(e.message)}</p>`}}

function renderHistory(){
 const h=[...state.user.history].sort((a,b)=>b.date-a.date),errors={};h.forEach(x=>Object.entries(x.errors||{}).forEach(([k,v])=>errors[k]=(errors[k]||0)+v));const scored=h.filter(x=>Number.isFinite(x.score));const avg=scored.length?Math.round(scored.reduce((a,x)=>a+x.score,0)/scored.length):0;const topErrors=Object.entries(errors).sort((a,b)=>b[1]-a[1]).slice(0,6);
 const topicCounts={};h.forEach(x=>(x.dialogueIds||[]).forEach(id=>{const t=state.byId[id]?.topic;if(t)topicCounts[t]=(topicCounts[t]||0)+1}));const maxTopic=Math.max(1,...Object.values(topicCounts));
 $('#app').innerHTML=page(`<section class="hero"><div class="card"><div class="eyebrow">Performance history</div><h1 style="font-size:52px">Patterns beat guesses.</h1><p>Your saved practice ratings reveal recurring weaknesses: missing details, numbers, terminology, register, or delivery. Recordings remain session-only for privacy; summaries stay in this browser.</p></div><div class="card"><h2>Overview</h2><div class="stats"><div class="stat"><strong>${h.length}</strong><span class="muted">saved attempts</span></div><div class="stat"><strong>${scored.length?avg+'%':'—'}</strong><span class="muted">average practice rating</span></div><div class="stat"><strong>${state.user.weak.length}</strong><span class="muted">weak segments flagged</span></div><div class="stat"><strong>${state.user.completed.length}</strong><span class="muted">dialogues completed</span></div></div></div></section><section class="section error-summary"><div class="card"><h3>Common error tags</h3>${topErrors.length?topErrors.map(([k,v])=>`<div style="margin:10px 0"><div class="dialogue-banner" style="margin:0"><span>${esc(k)}</span><strong>${v}</strong></div><div class="bar"><span style="width:${Math.min(100,v/Math.max(1,topErrors[0][1])*100)}%"></span></div></div>`).join(''):'<p class="muted">Tag errors during review to build this profile.</p>'}</div><div class="card"><h3>Topic exposure</h3>${Object.entries(topicCounts).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div style="margin:10px 0"><div class="dialogue-banner" style="margin:0"><span>${esc(k)}</span><strong>${v}</strong></div><div class="bar"><span style="width:${v/maxTopic*100}%"></span></div></div>`).join('')||'<p class="muted">Complete a session to start tracking topics.</p>'}</div><div class="card"><h3>Next focus</h3><p class="muted">${topErrors.length?`Your most frequent tagged issue is <strong style="color:var(--text)">${esc(topErrors[0][0])}</strong>. Use Quick Drill plus a weak-topic dialogue before the next strict mock.`:'Complete and review a mock exam, then use the error tags to generate a targeted study pattern.'}</p><div class="actions"><button class="btn primary" onclick="renderDrillSetup()">Quick drill</button><button class="btn" onclick="renderMockPicker()">Mock exam</button></div></div></section><section class="section card"><div class="section-head"><div><h2>Previous results</h2></div>${h.length?'<button class="btn danger" onclick="clearHistory()">Clear history</button>':''}</div>${h.length?h.map(x=>historyRow(x)).join(''):'<div class="empty">No saved attempts yet.</div>'}</section>`,'history')
}
function historyRow(x){const names=(x.dialogueIds||[]).map(id=>state.byId[id]?.title||id).join(' + ');return `<div class="history-row"><div><strong>${labelMode(x.mode)}</strong> · ${new Date(x.date).toLocaleDateString()}<div class="muted">${esc(names)}</div><div class="kicker">${x.duration?fmtTime(x.duration):''}${x.repeats!=null?` · repeats ${x.repeats}`:''}${x.rated!=null?` · ${x.rated} segments rated`:''}</div></div><div style="text-align:right"><strong style="font-size:24px">${Number.isFinite(x.score)?x.score+'%':'—'}</strong><div><button class="btn" onclick="redoHistory('${x.id}')">Redo</button></div></div></div>`}
function clearHistory(){if(confirm('Clear saved attempt history? Favourites and weak-segment flags will be kept.')){state.user.history=[];state.user.completed=[];saveUser();renderHistory()}}
function redoHistory(id){const x=state.user.history.find(y=>y.id===id);if(!x)return;if(x.mode==='mock'){const first=x.dialogueIds?.[0],idx=testPairs().findIndex(p=>p[0].id===first);startMock(Math.max(0,idx))}else if(x.mode==='practice')startPractice(x.dialogueIds[0]);else renderDrillSetup()}

function finishSession(){if(!state.session)return;stopPlayback();clearInterval(state.timer);clearInterval(state.session.interpretTimer);if(state.recorder?.state==='recording')state.recorder.stop();state.session.endedAt=Date.now();for(const id of state.session.dialogueIds||[])markCompleted(id);saveSessionToHistory(state.session);renderPerformance(state.session)}
function saveSessionToHistory(s){const metrics=sessionMetrics(s),duration=Math.max(1,Math.round(((s.endedAt||Date.now())-s.startedAt)/1000));const summary={id:s.id,date:s.endedAt||Date.now(),mode:s.mode,dialogueIds:s.dialogueIds||[...new Set((s.queue||[]).map(q=>q.did))],duration,repeats:s.mode==='mock'?Object.values(s.repeats||{}).reduce((a,b)=>a+b,0):null,score:metrics.score,rated:metrics.rated,errors:metrics.errors};const i=state.user.history.findIndex(x=>x.id===s.id);if(i>=0)state.user.history[i]=summary;else state.user.history.push(summary);state.user.history=state.user.history.slice(-100);saveUser()}
function sessionMetrics(s=state.session){const marks=Object.values(s?.marks||{}),rated=marks.filter(m=>m.rating),points={strong:3,minor:2,needs:1};const score=rated.length?Math.round(rated.reduce((a,m)=>a+(points[m.rating]||0),0)/(rated.length*3)*100):null;const errors={};rated.forEach(m=>(m.tags||[]).forEach(t=>errors[t]=(errors[t]||0)+1));return{score,rated:rated.length,errors}}
function renderPerformance(s=state.session){if(!s)return go('history');state.session=s;const metrics=sessionMetrics(s),items=s.mode==='drill'?(s.queue||[]).map(q=>({d:state.byId[q.did],seg:state.byId[q.did].segments[q.n-1]})):(s.dialogueIds||[]).flatMap(id=>state.byId[id].segments.map(seg=>({d:state.byId[id],seg})));const repeats=s.mode==='mock'?Object.values(s.repeats||{}).reduce((a,b)=>a+b,0):0;$('#app').innerHTML=page(`<section class="hero"><div class="card"><div class="eyebrow">Review</div><h1 style="font-size:52px">Meaning first.<br>Then delivery.</h1><p>Rate each segment and tag the actual error pattern. Your saved percentage is a personal practice metric, not an official exam score.</p><div class="actions"><button class="btn primary" onclick="saveSessionToHistory(state.session);go('history')">Save & view history</button><button class="btn" onclick="go('dashboard')">Dashboard</button></div></div><div class="card"><h2>Session</h2><div class="stats"><div class="stat"><strong>${metrics.score==null?'—':metrics.score+'%'}</strong><span class="muted">practice rating</span></div><div class="stat"><strong>${metrics.rated}/${items.length}</strong><span class="muted">segments rated</span></div><div class="stat"><strong>${fmtTime(((s.endedAt||Date.now())-s.startedAt)/1000)}</strong><span class="muted">elapsed</span></div><div class="stat"><strong>${repeats}</strong><span class="muted">repeats</span></div></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Segment review</div><h2>${items.length} source segments</h2></div></div><div class="review-list">${items.map(({d,seg},i)=>reviewItem(d,seg)).join('')}</div></section>`,'history')}
function reviewItem(d,seg){const k=sessionKey(d.id,seg.n),m=state.session.marks[k]||{rating:null,tags:[]};return `<details class="review-item"><summary>${d.id} · S${seg.n} · ${seg.source_lang==='en'?'EN → YUE':'YUE → EN'} ${isWeak(d.id,seg.n)?'· ⚑ weak':''}</summary><div class="compare-grid" style="margin-top:12px"><div><div class="kicker">Source</div><div class="source-box">${esc(seg.source)}</div></div><div><div class="kicker">Model interpretation</div><div class="model-box">${esc(seg.model)}</div></div></div>${state.recordings[k]?`<div class="actions"><button class="btn" onclick="playMyRecording('${d.id}',${seg.n})">Listen to my recording</button></div>`:''}<div class="rating-row">${[['strong','Strong'],['minor','Minor issue'],['needs','Needs work']].map(([v,l])=>`<button class="rating ${m.rating===v?'on':''}" onclick="setMark('${k}','rating','${v}','review')">${l}</button>`).join('')}</div><div class="rating-row">${ERROR_TAGS.map(t=>`<button class="tag ${(m.tags||[]).includes(t)?'on':''}" onclick="setMark('${k}','tag','${esc(t)}','review')">${esc(t)}</button>`).join('')}</div></details>`}

class AudioEngine{
 constructor(){this.audio=new Audio();this.cache=new Map();this.stopToken=0}
 base(){if(['localhost','127.0.0.1'].includes(location.hostname))return'/assets/audio-bundles/';return state.config?.audioBase||'/assets/audio-bundles/'}
 async dialogueURL(id){if(this.cache.has(id))return this.cache.get(id);const info=state.audioManifest?.dialogues?.[id];if(!info)throw new Error('Audio manifest unavailable');const url=this.base()+info.bundle;const r=await fetch(url,{headers:{Range:`bytes=${info.offset}-${info.offset+info.length-1}`}});if(!r.ok)throw new Error(`MP3 fetch failed (${r.status})`);let ab=await r.arrayBuffer();if(r.status!==206&&ab.byteLength!==info.length){if(ab.byteLength<info.offset+info.length)throw new Error('Audio bundle is incomplete');ab=ab.slice(info.offset,info.offset+info.length)}const blobURL=URL.createObjectURL(new Blob([ab],{type:'audio/mpeg'}));this.cache.set(id,blobURL);return blobURL}
 async play(id,segIndex,rate=1,onDone){const info=state.audioManifest?.dialogues?.[id];if(!info)throw new Error('No bundled audio');const t=info.segments[segIndex];if(!t)throw new Error('Segment audio missing');const url=await this.dialogueURL(id);const token=++this.stopToken;this.audio.pause();if(this.audio.src!==url){this.audio.src=url;this.audio.load();await new Promise((res,rej)=>{if(this.audio.readyState>=1)return res();const ok=()=>{cleanup();res()},bad=()=>{cleanup();rej(new Error('Audio metadata failed'))},cleanup=()=>{this.audio.removeEventListener('loadedmetadata',ok);this.audio.removeEventListener('error',bad)};this.audio.addEventListener('loadedmetadata',ok,{once:true});this.audio.addEventListener('error',bad,{once:true})})}this.audio.playbackRate=rate;this.audio.currentTime=Math.max(0,t.start-.015);await this.audio.play();const monitor=()=>{if(token!==this.stopToken)return;if(this.audio.currentTime>=t.end-.012||this.audio.ended){this.audio.pause();if(onDone)onDone();return}requestAnimationFrame(monitor)};requestAnimationFrame(monitor)}
 stop(){this.stopToken++;this.audio.pause()}
}
function normVoice(v){return `${v?.name||''} ${v?.lang||''}`.toLowerCase()}
function pickVoice(lang){
 const y=lang==='yue',vs=state.voices||[];
 const eligible=vs.filter(v=>y?(/\byue\b|canton|zh[-_]HK|hong kong/i.test(`${v.lang} ${v.name}`)):(/en[-_]AU|austral/i.test(`${v.lang} ${v.name}`)));
 if(!eligible.length)return null;
 const quality=/natural|premium|enhanced|neural|google|microsoft|siri|ava|zoe|karen|lee/i;
 return eligible.sort((a,b)=>Number(quality.test(normVoice(b)))-Number(quality.test(normVoice(a))))[0]
}
function speakFallback(seg,rate,onDone){return new Promise((resolve,reject)=>{
 if(!('speechSynthesis'in window)){reject(new Error('No browser speech engine'));return}const v=pickVoice(seg.source_lang);if(!v){reject(new Error(seg.source_lang==='yue'?'No Cantonese fallback voice detected':'No Australian-English fallback voice detected'));return}
 const u=new SpeechSynthesisUtterance(seg.source);u.lang=seg.source_lang==='en'?'en-AU':'yue-HK';u.voice=v;u.rate=Number(rate||1)*(seg.source_lang==='yue'?1.12:1);u.pitch=seg.role==='C'?1.03:.98;
 u.onend=()=>chime(()=>{onDone&&onDone();resolve()});u.onerror=()=>reject(new Error('Browser speech fallback failed'));speechSynthesis.speak(u)
})}
async function playSource(d,seg,rate,onDone){
 stopPlayback();const st=$('#audioStatus'),btn=$('#playBtn');if(st)st.textContent='Loading calibrated source audio…';if(btn)btn.disabled=true;
 try{await state.audioEngine.play(d.id,seg.n-1,rate,()=>{if(st)st.textContent='Chime finished. Interpret now.';if(btn)btn.disabled=false;onDone&&onDone()});if(state.session)state.session.audioMode='mp3';if(st)st.textContent='Playing calibrated MP3 source audio…'}
 catch(e){if(st)st.textContent='MP3 unavailable — using device-dependent speech fallback.';try{await speakFallback(seg,rate,()=>{if(btn)btn.disabled=false;onDone&&onDone()});if(state.session)state.session.audioMode='speech'}catch(f){if(st)st.textContent=`Audio unavailable: ${f.message}`}}
 finally{if(btn&&state.audioEngine.audio.paused&&!speechSynthesis?.speaking)btn.disabled=false}
}
function stopPlayback(){state.audioEngine?.stop();if('speechSynthesis'in window)speechSynthesis.cancel()}
function chime(done){try{const c=new(window.AudioContext||window.webkitAudioContext)(),now=c.currentTime;[880,1320].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=now+i*.18;o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.13,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.15)});setTimeout(()=>{c.close();done&&done()},600)}catch{done&&done()}}

async function toggleRecord(){if(state.recorder?.state==='recording'){state.recorder.stop();return}try{state.media=state.media||await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(state.media);state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=()=>{const cur=currentRecordingKey();if(cur)state.recordings[cur]=URL.createObjectURL(new Blob(state.chunks,{type:state.recorder.mimeType}));const b=$('#recordBtn');if(b){b.textContent='● Start recording';b.classList.remove('danger')}const rs=$('#recStatus');if(rs)rs.textContent='Recording saved for this session.';renderRecordingButton()};state.recorder.start();const b=$('#recordBtn');if(b){b.textContent='■ Stop recording';b.classList.add('danger')}const rs=$('#recStatus');if(rs)rs.innerHTML='<span class="recording">● Recording…</span>'}catch{alert('Microphone access is needed to record your interpretation.')}}
function currentRecordingKey(){if(!state.session)return null;if(state.session.mode==='mock'){const {d,seg}=currentMock();return sessionKey(d.id,seg.n)}if(state.session.mode==='practice'){const {d,seg}=currentPractice();return sessionKey(d.id,seg.n)}if(state.session.mode==='drill'){const {d,seg}=currentDrill();return sessionKey(d.id,seg.n)}return null}
function renderRecordingButton(){const key=currentRecordingKey();$$('button').filter(b=>b.textContent.includes('Listen to mine')).forEach(b=>b.disabled=!state.recordings[key])}
function playMyRecording(id,n){const u=state.recordings[sessionKey(id,n)];if(u)new Audio(u).play()}
function stopAll(){stopPlayback();clearInterval(state.timer);clearInterval(state.session?.interpretTimer);if(state.recorder?.state==='recording')state.recorder.stop()}

boot();
