#!/usr/bin/env python3
from pathlib import Path

p=Path('app.js')
s=p.read_text(encoding='utf-8')
repls={
"function nextMock(){stopPlayback();if(state.recorder?.state==='recording')state.recorder.stop();const s=state.session,d=state.byId[s.dialogueIds[s.di]];if(s.si<d.segments.length-1){s.si++;renderMock();return}markCompleted(d.id);if(s.di===0){s.di=1;s.si=0;renderMock();return}markCompleted(state.byId[s.dialogueIds[1]].id);finishSession()}":"async function nextMock(){stopPlayback();await stopRecordingIfNeeded();const s=state.session,d=state.byId[s.dialogueIds[s.di]];if(s.si<d.segments.length-1){s.si++;renderMock();return}markCompleted(d.id);if(s.di===0){s.di=1;s.si=0;renderMock();return}markCompleted(state.byId[s.dialogueIds[1]].id);await finishSession()}",
"function nextPractice(){const s=state.session,{d}=currentPractice();if(s.si<d.segments.length-1){s.si++;renderPractice();return}markCompleted(d.id);s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}":"async function nextPractice(){stopPlayback();await stopRecordingIfNeeded();const s=state.session,{d}=currentPractice();if(s.si<d.segments.length-1){s.si++;renderPractice();return}markCompleted(d.id);s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}",
"function nextDrill(){const s=state.session;if(s.qi<s.queue.length-1){s.qi++;renderDrill();return}s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}":"async function nextDrill(){stopPlayback();await stopRecordingIfNeeded();const s=state.session;if(s.qi<s.queue.length-1){s.qi++;renderDrill();return}s.endedAt=Date.now();saveSessionToHistory(s);renderPerformance(s)}",
"function finishSession(){if(!state.session)return;stopPlayback();clearInterval(state.timer);clearInterval(state.session.interpretTimer);if(state.recorder?.state==='recording')state.recorder.stop();state.session.endedAt=Date.now();for(const id of state.session.dialogueIds||[])markCompleted(id);saveSessionToHistory(state.session);renderPerformance(state.session)}":"async function finishSession(){if(!state.session||state.session.finishing)return;state.session.finishing=true;stopPlayback();clearInterval(state.timer);clearInterval(state.session.interpretTimer);await stopRecordingIfNeeded();state.session.endedAt=Date.now();for(const id of state.session.dialogueIds||[])markCompleted(id);saveSessionToHistory(state.session);renderPerformance(state.session)}",
"async function toggleRecord(){if(state.recorder?.state==='recording'){state.recorder.stop();return}try{state.media=state.media||await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(state.media);state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=()=>{const cur=currentRecordingKey();if(cur)state.recordings[cur]=URL.createObjectURL(new Blob(state.chunks,{type:state.recorder.mimeType}));const b=$('#recordBtn');if(b){b.textContent='● Start recording';b.classList.remove('danger')}const rs=$('#recStatus');if(rs)rs.textContent='Recording saved for this session.';renderRecordingButton()};state.recorder.start();const b=$('#recordBtn');if(b){b.textContent='■ Stop recording';b.classList.add('danger')}const rs=$('#recStatus');if(rs)rs.innerHTML='<span class=\"recording\">● Recording…</span>'}catch{alert('Microphone access is needed to record your interpretation.')}}":"async function toggleRecord(){if(state.recorder?.state==='recording'){await stopRecordingIfNeeded();return}try{state.media=state.media||await navigator.mediaDevices.getUserMedia({audio:true});const recordKey=currentRecordingKey(),recordSessionId=state.session?.id,chunks=[];const recorder=new MediaRecorder(state.media);state.recorder=recorder;recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{if(recordKey&&state.session?.id===recordSessionId)state.recordings[recordKey]=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));if(currentRecordingKey()===recordKey&&state.session?.id===recordSessionId){const b=$('#recordBtn');if(b){b.textContent='● Start recording';b.classList.remove('danger')}const rs=$('#recStatus');if(rs)rs.textContent='Recording saved for this session.';renderRecordingButton()}};recorder.start();const b=$('#recordBtn');if(b){b.textContent='■ Stop recording';b.classList.add('danger')}const rs=$('#recStatus');if(rs)rs.innerHTML='<span class=\"recording\">● Recording…</span>'}catch{alert('Microphone access is needed to record your interpretation.')}}\nfunction stopRecordingIfNeeded(){const recorder=state.recorder;if(!recorder||recorder.state!=='recording')return Promise.resolve();return new Promise(resolve=>{recorder.addEventListener('stop',resolve,{once:true});recorder.stop()})}"
}
for old,new in repls.items():
    if old not in s:
        raise SystemExit('guard failed: expected app.js block not found; refusing to patch a changed v2 app')
    s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('recording race patch applied')
