#!/usr/bin/env python3
from pathlib import Path
p=Path('app.js')
s=p.read_text(encoding='utf-8')
repls={
"const RAW_MAIN='https://raw.githubusercontent.com/SzeChunYiu/CCL-exam/main/';\nconst localHost=()=>['localhost','127.0.0.1'].includes(location.hostname);\nconst asset=(path)=>localHost()?`/${path}`:`${RAW_MAIN}${path}`;":"const localHost=()=>['localhost','127.0.0.1'].includes(location.hostname);\n// Vercel serves the checked-out branch assets directly. This also makes preview deployments self-contained.\nconst asset=(path)=>`/${String(path).replace(/^\\//,'')}`;",
"const state={dialogues:[],byId:{},glossary:[],studyIndex:[],summary:null,audioManifest:null,config:null,user:null,view:'dashboard',session:null,timer:null,voices:[],media:null,recorder:null,chunks:[],recordings:{},audioEngine:null,speechDelay:null};":"const state={dialogues:[],byId:{},glossary:[],studyIndex:[],summary:null,audioManifest:null,remoteAudio:null,config:null,user:null,view:'dashboard',session:null,timer:null,voices:[],media:null,recorder:null,chunks:[],recordings:{},audioEngine:null,speechDelay:null};",
"return `<header class=\"topbar\"><div class=\"brand\" onclick=\"go('dashboard')\" style=\"cursor:pointer\"><div class=\"mark\">CCL</div><div>CCL Exam Lab<div class=\"kicker\">English ⇄ Cantonese</div></div></div><nav class=\"nav\">${items.map(([v,l])=>`<button class=\"${active===v?'active':''}\" onclick=\"go('${v}')\">${l}</button>`).join('')}</nav><span class=\"pill ${state.audioManifest?'ok':'warn'}\">${state.audioManifest?'Calibrated MP3 ready':'Speech fallback'}</span></header>`":"const audioLabel=state.remoteAudio?'Supabase MP3':(state.audioManifest?'Bundled MP3 ready':'Speech fallback'); return `<header class=\"topbar\"><div class=\"brand\" onclick=\"go('dashboard')\" style=\"cursor:pointer\"><div class=\"mark\">CCL</div><div>CCL Exam Lab<div class=\"kicker\">English ⇄ Cantonese</div></div></div><nav class=\"nav\">${items.map(([v,l])=>`<button class=\"${active===v?'active':''}\" onclick=\"go('${v}')\">${l}</button>`).join('')}</nav><span class=\"pill ${state.audioManifest?'ok':'warn'}\">${audioLabel}</span></header>`",
"  let am=null;\n  if(cfg.audioManifestUrl){am=await fetch(cfg.audioManifestUrl,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)}\n  if(!am){am=await getJSON('data/audio_manifest.json').catch(()=>null)}\n  state.dialogues=d;state.byId=Object.fromEntries(d.map(x=>[x.id,x]));state.glossary=g;state.studyIndex=si;state.summary=sm;state.config=cfg;state.audioManifest=am;state.audioEngine=new AudioEngine();renderDashboard();":"  let am=null;\n  if(cfg.audioManifestUrl){am=await fetch(cfg.audioManifestUrl,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)}\n  if(!am){am=await getJSON('data/audio_manifest.json').catch(()=>null)}\n  const remote=await getJSON('data/audio_remote.json').catch(()=>null);\n  state.dialogues=d;state.byId=Object.fromEntries(d.map(x=>[x.id,x]));state.glossary=g;state.studyIndex=si;state.summary=sm;state.config=cfg;state.audioManifest=am;state.remoteAudio=remote?.baseUrl?remote:null;state.audioEngine=new AudioEngine();renderDashboard();",
" base(){if(['localhost','127.0.0.1'].includes(location.hostname))return'/assets/audio-bundles/';return state.config?.audioBase||'/assets/audio-bundles/'}":" base(){return state.remoteAudio?.baseUrl||state.config?.audioBase||'/assets/audio-bundles/'}"
}
for old,new in repls.items():
    if old not in s:
        raise SystemExit('guard failed: expected app.js block not found; refusing to patch changed code')
    s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('Supabase audio patch applied')
