const DATA_URL='/practice_pack/dialogues_metadata.json';
const $=(s)=>document.querySelector(s);
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={data:[],mode:'home',test:[],dialogueIndex:0,segmentIndex:0,repeats:[0,0],startedAt:0,timeLeft:1200,timer:null,media:null,recorder:null,chunks:[],recordings:{},notes:{},responses:{},voices:[],speechDone:true};

function savePrefs(){localStorage.setItem('cclPrefs',JSON.stringify({voiceRate:Number($('#rate')?.value||1),topic:$('#topic')?.value||'All'}));}
function prefs(){try{return JSON.parse(localStorage.getItem('cclPrefs'))||{}}catch{return {}}}
function loadVoices(){state.voices=speechSynthesis?.getVoices?.()||[]}
if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}

async function boot(){
  const app=$('#app'); app.innerHTML='<main class="shell"><div class="card"><h2>Loading 100-dialogue practice bank…</h2><p class="muted">Preparing mock tests and topic practice.</p></div></main>';
  try{const r=await fetch(DATA_URL); if(!r.ok)throw new Error('Dataset not found'); state.data=await r.json(); renderHome();}
  catch(e){app.innerHTML=`<main class="shell"><div class="card"><h2>Could not load the practice bank</h2><p class="muted">${esc(e.message)}</p></div></main>`}
}

function topics(){return [...new Set(state.data.map(d=>d.topic))]}
function tests(){let out=[];for(let i=0;i<state.data.length;i+=2)out.push([state.data[i],state.data[i+1]]);return out}
function renderHome(){
 const p=prefs(); const list=tests();
 $('#app').innerHTML=`<main class="shell">
 <header class="topbar"><div class="brand"><div class="mark">CCL</div><div>CCL Exam Lab<br><span class="muted" style="font-size:12px">English ⇄ Cantonese</span></div></div><span class="pill">Australia-focused</span></header>
 <section class="hero"><div class="card"><div class="eyebrow">NAATI-style practice</div><h1>Train the skill.<br>Not the script.</h1><p>Run blind English–Cantonese mock dialogues with segment audio, repeat tracking, a 20-minute exam clock, microphone recording and answer review.</p><div class="actions"><button class="btn primary" onclick="startTest(0)">Start Mock Test 01</button><button class="btn" onclick="randomTest()">Random mock</button></div></div>
 <div class="card"><h2>Practice bank</h2><div class="stats"><div class="stat"><strong>${state.data.length}</strong><span class="muted">dialogues</span></div><div class="stat"><strong>${list.length}</strong><span class="muted">mock tests</span></div><div class="stat"><strong>${state.data.reduce((a,d)=>a+d.segments.length,0)}</strong><span class="muted">segments</span></div><div class="stat"><strong>${topics().length}</strong><span class="muted">topics</span></div></div></div></section>
 <section class="section"><div class="dialogue-banner"><div><div class="eyebrow">Practice library</div><h2>Choose a mock exam</h2></div></div><div class="toolbar"><select id="topic" class="select" onchange="filterTests();savePrefs()"><option>All</option>${topics().map(t=>`<option ${p.topic===t?'selected':''}>${esc(t)}</option>`).join('')}</select><label class="pill">Voice speed <select id="rate" class="select" style="padding:4px 6px;border:0" onchange="savePrefs()"><option value="0.9">0.9×</option><option value="1" ${!p.voiceRate||p.voiceRate===1?'selected':''}>1.0×</option><option value="1.08" ${p.voiceRate===1.08?'selected':''}>1.08×</option></select></label></div><div id="testGrid" class="grid"></div></section>
 <div class="footer">Original practice material. Synthetic/browser speech is for training, not official NAATI audio.</div></main>`; filterTests();
}
function filterTests(){const t=$('#topic')?.value||'All';const list=tests();$('#testGrid').innerHTML=list.map((pair,i)=>({pair,i})).filter(x=>t==='All'||x.pair.some(d=>d.topic===t)).map(({pair,i})=>`<article class="exam-card"><span class="pill accent">Mock ${String(i+1).padStart(2,'0')}</span><h3>${esc(pair[0].title)}</h3><div class="muted">${esc(pair[0].topic)}</div><p class="muted" style="margin:8px 0">+</p><h3>${esc(pair[1].title)}</h3><div class="muted">${esc(pair[1].topic)}</div><div class="actions"><button class="btn" onclick="startTest(${i})">Open exam</button></div></article>`).join('')}
function randomTest(){startTest(Math.floor(Math.random()*tests().length))}
function startTest(i){state.test=tests()[i];state.dialogueIndex=0;state.segmentIndex=0;state.repeats=[0,0];state.timeLeft=1200;state.startedAt=Date.now();state.recordings={};state.notes={};state.responses={};renderExam();clearInterval(state.timer);state.timer=setInterval(tick,1000)}
function tick(){state.timeLeft=Math.max(0,1200-Math.floor((Date.now()-state.startedAt)/1000));const el=$('#timer');if(el){el.textContent=fmt(state.timeLeft);el.classList.toggle('warn',state.timeLeft<180)}if(state.timeLeft<=0){clearInterval(state.timer);finishExam()}}
function fmt(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function current(){return state.test[state.dialogueIndex].segments[state.segmentIndex]}
function key(){return`${state.dialogueIndex}-${state.segmentIndex}`}
function renderExam(){
 const d=state.test[state.dialogueIndex],s=current(),doneBefore=state.dialogueIndex*12+state.segmentIndex,total=state.test.reduce((a,x)=>a+x.segments.length,0);
 $('#app').innerHTML=`<div class="exam-head"><div class="exam-head-inner"><div><strong>Mock Exam</strong><div class="muted" style="font-size:12px">Dialogue ${state.dialogueIndex+1} of 2</div></div><div id="timer" class="timer">${fmt(state.timeLeft)}</div><button class="btn danger" onclick="finishExam()">Finish</button></div><div class="progress"><span style="width:${doneBefore/total*100}%"></span></div></div>
 <main class="exam-shell"><div class="dialogue-banner"><div><span class="pill">${esc(d.topic)}</span><h2 style="margin-top:8px">${esc(d.title)}</h2></div><div class="repeat-count">Repeats this dialogue: <strong>${state.repeats[state.dialogueIndex]}</strong><br><span>${state.repeats[state.dialogueIndex]<=1?'1 repeat is your practice allowance':'Extra repeats used'}</span></div></div>
 <section class="card segment-card"><div class="segment-num">SEGMENT ${s.n} / ${d.segments.length}</div><div class="language">${s.source_lang==='en'?'ENGLISH → CANTONESE':'CANTONESE → ENGLISH'}</div><div class="listen-icon">◖))</div><div id="promptStatus" class="prompt-hidden">Source text is hidden in exam mode.<br>Play the segment, interpret in first person, then continue.</div>
 <div class="segment-actions"><button id="playBtn" class="btn primary" onclick="speakSegment(false)">▶ Play segment</button><button class="btn" onclick="speakSegment(true)">↻ Repeat</button></div>
 <div class="recorder"><div id="recStatus" class="hint">Optional: record your interpretation for review.</div><div class="segment-actions"><button id="recordBtn" class="btn" onclick="toggleRecord()">● Start recording</button><button id="playRecBtn" class="btn" onclick="playRecording()" ${state.recordings[key()]?'':'disabled'}>Listen to mine</button></div></div>
 <textarea id="note" class="notes" placeholder="Optional notes / shorthand used…" oninput="state.notes[key()]=this.value">${esc(state.notes[key()]||'')}</textarea>
 <div class="segment-actions"><button class="btn primary" onclick="nextSegment()">${state.dialogueIndex===1&&state.segmentIndex===d.segments.length-1?'Finish exam':'Submit & next →'}</button></div><p class="hint">Tip: begin interpreting within about five seconds after the source finishes. Avoid third-person reporting.</p></section></main>`;
}
function pickVoice(lang){const isYue=lang==='yue';let vs=state.voices||[];const tests=isYue?[/yue/i,/canton/i,/zh[-_]HK/i,/Hong Kong/i]:[/en[-_]AU/i,/Australia/i];for(const rx of tests){const v=vs.find(x=>rx.test(`${x.lang} ${x.name}`));if(v)return v}return vs.find(x=>isYue?/zh/i.test(x.lang):/en/i.test(x.lang))}
function speakSegment(isRepeat){if(!('speechSynthesis'in window)){alert('Speech synthesis is not available in this browser.');return}if(isRepeat)state.repeats[state.dialogueIndex]++;speechSynthesis.cancel();const s=current(),u=new SpeechSynthesisUtterance(s.source);u.lang=s.source_lang==='en'?'en-AU':'zh-HK';u.rate=Number(prefs().voiceRate||1);const v=pickVoice(s.source_lang);if(v)u.voice=v;const b=$('#playBtn');if(b)b.disabled=true;u.onend=()=>{if(b)b.disabled=false;chime()};u.onerror=()=>{if(b)b.disabled=false};speechSynthesis.speak(u);const rc=document.querySelector('.repeat-count');if(rc&&isRepeat)rc.innerHTML=`Repeats this dialogue: <strong>${state.repeats[state.dialogueIndex]}</strong><br><span>${state.repeats[state.dialogueIndex]<=1?'1 repeat is your practice allowance':'Extra repeats used'}</span>`}
function chime(){try{const c=new (window.AudioContext||window.webkitAudioContext)(),now=c.currentTime;[880,1320].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.17);g.gain.exponentialRampToValueAtTime(.13,now+i*.17+.02);g.gain.exponentialRampToValueAtTime(.0001,now+i*.17+.13);o.connect(g).connect(c.destination);o.start(now+i*.17);o.stop(now+i*.17+.15)})}catch{}}
async function toggleRecord(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();return}try{state.media=state.media||await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(state.media);state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=()=>{state.recordings[key()]=URL.createObjectURL(new Blob(state.chunks,{type:state.recorder.mimeType}));const p=$('#playRecBtn');if(p)p.disabled=false;const r=$('#recordBtn');if(r){r.textContent='● Start recording';r.classList.remove('danger')}$('#recStatus').textContent='Recording saved for this session.'};state.recorder.start();$('#recordBtn').textContent='■ Stop recording';$('#recordBtn').classList.add('danger');$('#recStatus').innerHTML='<span class="recording">● Recording…</span>'}catch(e){alert('Microphone access is needed to record your interpretation.') }}
function playRecording(){const u=state.recordings[key()];if(u)new Audio(u).play()}
function nextSegment(){if(state.recorder?.state==='recording')state.recorder.stop();const d=state.test[state.dialogueIndex];if(state.segmentIndex<d.segments.length-1){state.segmentIndex++;renderExam();return}if(state.dialogueIndex===0){state.dialogueIndex=1;state.segmentIndex=0;renderExam();return}finishExam()}
function finishExam(){clearInterval(state.timer);speechSynthesis?.cancel?.();if(state.recorder?.state==='recording')state.recorder.stop();renderReview()}
function renderReview(){const elapsed=Math.min(1200,Math.floor((Date.now()-state.startedAt)/1000));const items=state.test.flatMap((d,di)=>d.segments.map((s,si)=>({d,s,di,si})));$('#app').innerHTML=`<main class="shell"><header class="topbar"><div class="brand"><div class="mark">CCL</div><div>Exam review</div></div><button class="btn" onclick="renderHome()">← Dashboard</button></header><section class="hero"><div class="card"><div class="eyebrow">Completed</div><h1 style="font-size:42px">Review meaning,<br>then delivery.</h1><p>Compare your interpretation against each model. The model is one acceptable rendition, not the only correct wording.</p></div><div class="card"><h2>Session</h2><div class="stats"><div class="stat"><strong>${fmt(elapsed)}</strong><span class="muted">elapsed</span></div><div class="stat"><strong>${state.repeats.reduce((a,b)=>a+b,0)}</strong><span class="muted">repeats</span></div></div></div></section>
 <section class="section card"><h2>Self-assessment</h2><p class="muted">Score your whole performance from 1–5 in each dimension. This is a study aid, not an official NAATI score.</p>${['Meaning accuracy','Completeness / omissions','Numbers, names & dates','English delivery','Cantonese delivery','Register & Australian terminology'].map((x,i)=>`<div class="score-row"><label>${x}</label><input type="range" min="1" max="5" value="3" data-score oninput="calcScore()"></div>`).join('')}<div><span class="final-score" id="selfScore">60%</span> <span class="muted">self-rating</span></div></section>
 <section class="section"><div class="dialogue-banner"><div><div class="eyebrow">Answer review</div><h2>All 24 segments</h2></div></div><div class="review-list">${items.map(({d,s,di,si},i)=>`<article class="review-item"><div class="dialogue-banner"><div><span class="pill">${esc(d.topic)}</span> <span class="pill">D${di+1} · S${s.n}</span></div>${state.recordings[`${di}-${si}`]?`<button class="btn" onclick="new Audio(state.recordings['${di}-${si}']).play()">Listen to mine</button>`:''}</div><div class="muted">${s.source_lang==='en'?'English source':'Cantonese source'}</div><div class="source">${esc(s.source)}</div><div class="muted" style="margin-top:12px">Model interpretation</div><div class="model">${esc(s.model)}</div>${state.notes[`${di}-${si}`]?`<div class="hint" style="margin-top:10px">Your note: ${esc(state.notes[`${di}-${si}`])}</div>`:''}</article>`).join('')}</div></section><div class="footer">Use the error patterns you notice here to choose your next topic practice.</div></main>`;calcScore()}
function calcScore(){const xs=[...document.querySelectorAll('[data-score]')];if(!xs.length)return;const n=xs.reduce((a,x)=>a+Number(x.value),0)/(xs.length*5);$('#selfScore').textContent=Math.round(n*100)+'%'}
boot();
